
- hosts: localhost
  vars:
    - panel_plugins:
      - grafana-piechart-panel
      - grafana-clock-panel
      - jdbranham-diagram-panel
      - corpglory-progresslist-panel
      - natel-plotly-panel
      - grafana-polystat-panel
      - vonage-status-panel
      - flant-statusmap-panel
    - datasource_plugins:
      - simpod-json-datasource 
      - grafana-simple-json-datasource

  tasks:
    - name: Install nessesary package
      apt: 
          name: apt-transport-https
          state: present
          update_cache: yes
    
    - name: add grafana gpg key
      shell: curl https://packages.grafana.com/gpg.key | sudo apt-key add -
    
    - name: add grafana repo 
      apt_repository:
        repo: deb https://packages.grafana.com/oss/deb stable main
        state: present
        filename: grafana
    
    - name: Install grafana
      apt: 
          name: grafana
          state: present
          update_cache: yes

    - name: Install - update Grafana plugins
      grafana_plugin:
        name: "{{ item }}"
        version: latest
        state: present
      with_items:
        - "{{ panel_plugins }}"
        - "{{ datasource_plugins }}"


    - name: Enable and start grafana service
      service:
        name: grafana-server
        enabled: yes
        state: started

