#!/usr/bin/env ansible-playbook
- name: install postman application
  hosts: all 
  tasks:
    - name: Inspect postman file
      stat: path=/usr/bin/postman
      register: postman_file

    - name: Install postman
      when: not postman_file.stat.exists
      unarchive:
        remote_src: yes
        src: https://dl.pstmn.io/download/latest/linux64
        dest: /usr/bin

