---
- hosts: localhost
  become: true
  vars:
    audit_logs:
      - /var/log/audit/audit.log
      - /var/log/wtmp
      - /var/log/lastlog

  tasks:
    - name: clearing audit logs
      file:
        path: "{{ item }}"
        state: absent
      with_items: 
        - "{{ audit_logs }}"

    - name: cleaning up udev rules
      file:
        path: "/etc/udev/rules.d/70-persistent-net.rules"
        state: absent

    - name: cleaning up tmp directories
      shell: "rm -f -r {{ item }}"
      with_items:
        - /tmp/*
        - /var/tmp/*

    - name: cleaning up ssh keys
      command: "rm -f /etc/ssh/ssh_host_*"


