- name: Create an instance
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: brave-reason-247406
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/my-project.json
      zone: "asia-east2-b"
      region: "asia-east2"
      vmname: "vm-test-1"

  tasks:
   - name: create a disk
     gcp_compute_disk:
         name: "disk-instance-{{ vmname }}"
         size_gb: 10
         source_image: 'projects/gce-uefi-images/global/images/centos-7-v20190916'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: disk
   - name: create a network
     gcp_compute_network:
         name: 'network-instance'
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: network
   - name: create a address
     gcp_compute_address:
         name: "address-instance-{{ vmname }}"
         region: "{{ region }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
         state: present
     register: address
   - name: create a instance
     gcp_compute_instance:
         state: present
         name: "{{ vmname }}"
         machine_type: n1-standard-1
         disks:
           - auto_delete: true
             boot: true
             source: "{{ disk }}"
         network_interfaces:
             - network: "{{ network }}"
               access_configs:
                 - name: 'External NAT'
                   nat_ip: "{{ address }}"
                   type: 'ONE_TO_ONE_NAT'
         zone: "{{ zone }}"
         project: "{{ gcp_project }}"
         auth_kind: "{{ gcp_cred_kind }}"
         service_account_file: "{{ gcp_cred_file }}"
         scopes:
           - https://www.googleapis.com/auth/compute
     register: instance

   - name: Wait for SSH to come up
     wait_for: 
        host: "{{ address.address }}" 
        port: 22 
        delay: 10 
        timeout: 60

   - name: Add host to groupname
     add_host: 
       hostname: "{{ address.address }}" 
       groupname: new_instances
