- name: Get the instance List
  hosts: localhost
  gather_facts: no
  vars:
      gcp_project: brave-reason-247406
      gcp_cred_kind: serviceaccount
      gcp_cred_file: /home/my-project.json
      zone: "asia-south1-a"
      region: "asia-south1"
      vmname: "vm-test-2"

  tasks:
    - name: "a instance facts"
      gcp_compute_instance_facts:
        zone: "{{ zone }}"
        project: "{{ gcp_project }}"
        auth_kind: "{{ gcp_cred_kind }}"
        service_account_file: "{{ gcp_cred_file }}"
